####################
# set up languages
language: c

####################
# install packages
before_install:
  - travis/install-deps.sh

####################
# build script
script:
  - make -f Makefile.maintainer && ./configure --disable-oracle --disable-postgres && make && make check

####################
# branch configuration
branches:
  only:
  - master

####################
# os environments
os:
  - linux
  - osx

####################
# build matrix
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: required
    - os: osx
      osx_image: xcode7.3
  allow_failures:
    - os: osx
